### ISSUE TITLE
No standard saving Issues 

### ISSUE THREAD

**Issue by yuya495** [quietust/nintendulator#1]
Hello quietust's
I'm Japanese so I'm not good at English so I use Google Translate
I'm using the latest version of nintendulator, but I can't save normally

**Comment by quietust** [comment]
There are multiple things that Nintendulator can save: battery-backed cartridge expansion RAM, data written to FDS disk images, emulation savestates, input recordings, and AVI recorings.

Which one isn't working for you, and what error do you get?

**Comment by yuya495** [comment]
Battery backup type cartridge expansion RAM mapper４and mapper 16 are not saved properly.
I don't know because FDS hasn't been tested yet

バッテリーバックアップタイプのカートリッジ拡張RAMマッパー4およびマッパー16が正しく保存されません。
FDSはまだテストされていないのでわかりません

**Comment by yuya495** [comment]
mainly
主に

Image of nintendulator on top
The bottom is an image of Nestopia

上のNintendulatorの画像
一番下はネストピアのイメージ

mapper４
Downtown Special - Kunio-kun no Jidaigeki Da yo Zenin Shuugou! (Japan)
![amarec(20200503-021808)](https://user-images.githubusercontent.com/8580180/80871306-c8f3a980-8ce6-11ea-82a2-a549bc325b34.PNG)
![amarec(20200503-022820)](https://user-images.githubusercontent.com/8580180/80918546-89899380-8da0-11ea-8504-426e9b4932bd.PNG)

Mapper 16
Dragon Ball Z II-Gekishin Freeza !! (Japan)
![amarec(20200504-005748)](https://user-images.githubusercontent.com/8580180/80919000-9c9d6300-8da2-11ea-8732-1b599d6ff76f.PNG)
![amarec(20200503-023045)](https://user-images.githubusercontent.com/8580180/80918587-b342ba80-8da0-11ea-8079-b2867da76c92.PNG)


In the SRAM folder
![amarec(20200503-024031)](https://user-images.githubusercontent.com/8580180/80871479-da898100-8ce7-11ea-9bfe-81b86e9891cb.PNG)
![amarec(20200504-004953)](https://user-images.githubusercontent.com/8580180/80918708-53004880-8da1-11ea-89b7-ee664ffe9873.PNG)

Can not save normal game
が通常のゲームを保存できません

**Comment by yuya495** [comment]
Dragon Ball Z II Gekijin Frieza !! (Japan) Data is saved, but each time the data is saved, the character gradually disappears.
ドラゴンボールZ II激神フリーザ!! （日本）データを保存しますが、保存するたびに、キャラクターは徐々に消失してきます

**Comment by yuya495** [comment]
FDS could not be started
Am I doing something wrong?
FDSを開始できませんでした
私は何か間違ったことをしていますか

![amarec(20200503-140911)](https://user-images.githubusercontent.com/8580180/80899170-05a3bd00-8d48-11ea-8547-2c22e4c430bf.PNG)

**Comment by quietust** [comment]
I just identified a problem in mapper 16 which would've caused data corruption when writing to EEPROM - I've fixed it, and Dragon Ball Z II no longer appears to lose characters after each save. I've uploaded a new 0.985 build to my website which should include this fix.

As for Downtown Special, are you sure your ROM image has "Battery-backed SRAM" enabled? You can use "File -> Edit iNES Header" to check (and fix it if necessary).

As for Famicom Disk System support, only [fwNES-format](https://wiki.nesdev.com/w/index.php/FDS_file_format) FDS images are supported.

**Comment by yuya495** [comment]
The problem with Dragon Ball Z II and Downtown Special,
Solved thank you quietust
FDS still can't start
Is my FDS BIOS file name correct?
This screen does not appear


![image](https://user-images.githubusercontent.com/8580180/81159367-dbf6ca00-8fc3-11ea-97a5-94cafac09acb.png)
This screen does not appear

**Comment by yuya495** [comment]
Dragon Ball Z II and Downtown Special
Can now be saved successfully
FDS could be started safely
Thank you quietust

**Comment by yuya495** [comment]
SD Gundam Gaiden-Knight Gundam Monogatari 2-Hikari no Knight (Japan) creates SRAM file
Data cannot be saved normally
![amarec(20200507-231628)](https://user-images.githubusercontent.com/8580180/81306348-530e8a00-90ba-11ea-956a-468945fb6593.PNG)
